WebPyRobot/WebPyRobot/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'', include('backend.urls')),
    url(r'^admin/', admin.site.urls),
]

WebPyRobot/backend/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'backend'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.SignUp.as_view(), name='signUp'),
    url(r'^signup/thanks/$', views.thanks, name='signUpThanks'),
    url(r'^password_change$', views.password_change, name='password_change'),
    url(r'^fight/$', views.fight, name='fight'),
    url(r'^editor/$', views.editor, name='editor'),
    url(r'^editor/(?P<pk>[0-9]+)/$', views.editorDetail, name='editorDetail'),
    url(r'^inventory/$', views.inventory, name='inventory'),
    url(r'^market/$', views.market, name='market'),
    url(r'^parameter/$', views.parameter, name='parameter'),
    url(r'^help/$', views.help, name='help'),
    url(r'^agression/$', views.agression, name='agression'),
    url(r'^changeStuff/$', views.changeStuff, name='changeStuff'),
    url(r'^buyStuff/$', views.buyStuff, name='buyStuff'),
    url(r'^documentation/$', views.documentation, name='documentation'),

]

WebPyRobot/backend/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    money = models.PositiveIntegerField(default=0)
    avatar = models.ImageField(blank=True)
    agression = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def __getInventory__(self):
        wep = Inventory.objects.filter(owner=self,typeItem=TypeItem(pk=1))
        wOut = []
        for w in wep:
            wOut.append(getItemByType(w.item,TypeItem(pk=1)))
        arm = Inventory.objects.filter(owner=self, typeItem=TypeItem(pk=2))
        aOut =[]
        for a in arm:
            aOut.append(getItemByType(a.item,TypeItem(pk=2)))
        cater = Inventory.objects.filter(owner=self, typeItem=TypeItem(pk=3))
        cOut = []
        for c in cater:
            cOut.append(getItemByType(c.item, TypeItem(pk=3)))
        sys = Inventory.objects.filter(owner=self, typeItem=TypeItem(pk=4))
        sOut = []
        for s in sys:
            sOut.append(getItemByType(s.item, TypeItem(pk=4)))
        return [wOut, aOut, cOut, sOut]

class Ia(models.Model):
    owner = models.ForeignKey(UserProfile)
    name = models.CharField(max_length=50, default='')
    text = models.TextField()

    def __str__(self):
        return self.name
    def getIaByOwner(user):
        return Ia.objects.get(owner=user)


class Weapon(models.Model):

    name = models.CharField(max_length=200)
    price = models.PositiveIntegerField()
    attackValue = models.PositiveIntegerField()
    range = models.PositiveIntegerField()
    attackCost = models.PositiveIntegerField()
    pathIcon = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    def isInInventory(self,user):
        inv = Inventory.objects.filter(owner=user,typeItem=TypeItem(pk=1), item=self.pk)
        if inv.count() > 0 :
            return True
        else:
            return False

class Armor(models.Model):
    name = models.CharField(max_length=200)
    price = models.PositiveIntegerField()
    armorValue = models.PositiveIntegerField()
    pathIcon = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    def isInInventory(self,user):
        inv = Inventory.objects.filter(owner=user,typeItem=TypeItem(pk=2), item=self.pk)
        if inv.count() > 0 :
            return True
        else:
            return False

class Caterpillar(models.Model):
    name = models.CharField(max_length=200)
    price = models.PositiveIntegerField()
    moveValue = models.PositiveIntegerField()
    pathIcon = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    def isInInventory(self,user):
        inv = Inventory.objects.filter(owner=user,typeItem=TypeItem(pk=3), item=self.pk)
        if inv.count() > 0 :
            return True
        else:
            return False


class NavSystem(models.Model):
    name = models.CharField(max_length=200)
    price = models.PositiveIntegerField()
    actionValue = models.PositiveIntegerField()
    pathIcon = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    def isInInventory(self,user):
        inv = Inventory.objects.filter(owner=user,typeItem=TypeItem(pk=4), item=self.pk)
        if inv.count() > 0 :
            return True
        else:
            return False


class Tank(models.Model):
    owner = models.ForeignKey(UserProfile)
    ia = models.ForeignKey(Ia)
    weapon = models.ForeignKey(Weapon)
    armor = models.ForeignKey(Armor)
    caterpillar = models.ForeignKey(Caterpillar)
    navSystem = models.ForeignKey(NavSystem)

    def __str__(self):
        return self.owner.__str__()

class TypeItem (models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Inventory (models.Model):
    owner = models.ForeignKey(UserProfile)
    item = models.PositiveIntegerField()
    typeItem = models.ForeignKey(TypeItem)

    def __str__(self):
        return self.owner.__str__() + ",.... " + getItemByType(self.item, self.typeItem).__str__()


class DefaultIa (models.Model):
    text = models.TextField()

def getItemByType(itemIn,type):
    if type ==  TypeItem(pk=1) :
        return Weapon.objects.get(pk=itemIn)
    elif type == TypeItem(pk=2):
        return Armor.objects.get(pk=itemIn)
    elif type == TypeItem(pk=3):
        return Caterpillar.objects.get(pk=itemIn)
    elif type == TypeItem(pk=4) :
        return NavSystem.objects.get(pk=itemIn)

WebPyRobot/backend/forms.py
from django import forms


class SignUpForm (forms.Form):
    email = forms.EmailField(label='Email', required=True, widget=forms.TextInput(attrs={'class':'validate'}))
    username = forms.CharField(label='Pseudo', required=True, widget=forms.TextInput(attrs={'class':'validate'}))
    password = forms.CharField(label='Password', required=True, widget=forms.PasswordInput)

class ChangeDataForm(forms.Form):
    email = forms.EmailField(label='Email', required=True, disabled=True, widget=forms.TextInput(attrs={'class':'validate'}))
    username = forms.CharField(label='Pseudo', required=True, disabled=True, widget=forms.TextInput(attrs={'class':'validate'}))
    password = forms.CharField(label='Password', required=True, widget=forms.PasswordInput)

class CodeForm (forms.Form):
    ia = forms.CharField(label='ia')

WebPyRobot/backend/views.py
from dbus.service import Object
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.views.generic.edit import FormView
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

from backend.models import Weapon, Armor, Caterpillar, NavSystem, TypeItem, Inventory, DefaultIa
from .models import UserProfile, Tank, Ia
 #from .game.Game import Game, Robot

from .forms import SignUpForm
from .forms import ChangeDataForm

from .funct.funct import getItemByType,getBoolInventory
import json


# Create your views here.


def index(request):
    if request.user.is_authenticated:
        context = {'money' : UserProfile.objects.get(user=request.user).money,
                   'username' : request.user,
                   'pageIn' : 'accueil' ,
                   'agression': UserProfile.objects.get(user=request.user).agression,
                   'tank': Tank.objects.get(owner=UserProfile.objects.get(user=request.user))}
        return render(request, "backend/accueil.html", context)
    else:
        form = SignUpForm()
        context = { 'form' : form }
        return render(request, "backend/index.html",context)


@never_cache
def login(request):
    if request.user.is_authenticated:
        return redirect(reverse('backend:index'))
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        from django.contrib.auth import authenticate
        user = authenticate(username=username, password=password)
        if user is not None:
            from django.contrib.auth import login
            login(request, user)
            urlnext = request.POST.get('next', reverse('backend:index'))
            return redirect(urlnext)
        else:
            form = SignUpForm()
            context = {
                'form': form,
                'next': request.GET.get('next'),
                'error': 'Your username and password didn\'t match. Please try again.'
            }
            return render(request, 'backend/index.html', context)
    return render(request, 'backend/index.html',  {'next': request.GET.get('next')})


@never_cache
def logout(request):
    from django.contrib.auth import logout
    logout(request)
    return redirect(reverse('backend:index'))


class SignUp (FormView):
    from .forms import SignUpForm
    template_name = 'backend/index.html'
    form_class = SignUpForm

    def get_success_url(self):
        self.success_url = reverse('backend:signUpThanks')
        return super().get_success_url()

    def get(self, request, *args, **kwargs):
        from django.contrib.auth import logout
        logout(request)
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        email = form.cleaned_data['email']
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            user = User.objects.create_user(username, email, password)
            #create User
            UserProfile(user=user, money=0).save()
            #create ia file default
            userProfile = UserProfile.objects.get(user=user)
            i = Ia.objects.create(owner=userProfile, name=username+"\'s Ia", text=DefaultIa.objects.get(pk=1).text)
            #default Inventory
            Inventory.objects.create(owner=userProfile, item=1, typeItem=TypeItem(pk=1))
            Inventory.objects.create(owner=userProfile, item=1, typeItem=TypeItem(pk=2))
            Inventory.objects.create(owner=userProfile, item=1, typeItem=TypeItem(pk=3))
            Inventory.objects.create(owner=userProfile, item=1, typeItem=TypeItem(pk=4))
            #init tank
            w = getItemByType(1,TypeItem(pk=1))
            a = getItemByType(1,TypeItem(pk=2))
            c = getItemByType(1,TypeItem(pk=3))
            n = getItemByType(1,TypeItem(pk=4))
            Tank.objects.create(owner=userProfile, ia=i,weapon=w,armor=a,caterpillar=c,navSystem=n)
            return super(SignUp, self).form_valid(form)
        return super(SignUp, self).form_invalid(form)


def thanks(request):
    return render(request,"backend/thanks.html")

@login_required
def fight(request):
    import random
    from .game.Game import Game
    user1 = UserProfile.objects.get(user=request.user)
    nbuser = UserProfile.objects.all().count()
    user2 = UserProfile.objects.get(user=request.user)
    while True :
        alea = random.randrange(0, nbuser)
        try:
            user2 = UserProfile.objects.get(pk=alea)
        except UserProfile.DoesNotExist:
            pass
        if user1 != user2: break

    tank1 = Tank.objects.get(owner=user1)
    tank2 = Tank.objects.get(owner=user2)
    ia1 = Ia.objects.get(owner=user1)
    ia2 = Ia.objects.get(owner=user2)
    game = Game(tank1, tank2, ia1, ia2)
    res = game.run(0)
    user1.money = user1.money + 100
    user1.save()
    user2.money = user2.money + 100
    user2.save()
    context = {
        'result': res
    }
    return render(request, "backend/fight.html", context)

@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        print("ICI")
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            context = {'money': UserProfile.objects.get(user=request.user).money,
                       'username': request.user,
                       'pageIn': 'accueil',
                       'returnChange': "Les Informations ont bien été enregistré"}
            return render(request, "backend/accueil.html", context)
        else:
            context = {'money': UserProfile.objects.get(user=request.user).money,
                       'username': request.user,
                       'pageIn': 'accueil',
                       'returnChange': "Erreur"}
            return render(request, "backend/accueil.html", context)

@login_required
def editor(request):
    from .forms import CodeForm
    userprofile = UserProfile.objects.get(user=request.user)
    ia = Ia.objects.get(owner=userprofile)
    if request.method == 'POST':
        code_form = CodeForm(request.POST)
        if code_form.is_valid():
            useria = code_form.cleaned_data['ia']
            ia.text = useria
            ia.save()

    context = {
        'money': UserProfile.objects.get(user=request.user).money,
        'username': request.user,
        'pageIn': 'editor',
        'code': ia.text
    }
    return render(request, 'backend/editeur.html', context)


@login_required
def editorDetail(request, pk):
    return HttpResponse('page de l editor pour ' + pk)


@login_required
def market(request):
    currentUser = UserProfile.objects.get(user=request.user)

    context = {'money' : currentUser.money,
               'username' : request.user,
               'pageIn': 'market',
               'weapons': Weapon.objects.all(),
               'armors': Armor.objects.all(),
               'caterpillars': Caterpillar.objects.all(),
               'navSys': NavSystem.objects.all(),
               }
    return render(request, 'backend/boutique.html',context)

@login_required
def inventory(request):
    inventory = UserProfile.objects.get(user=request.user).__getInventory__()
    weapon = inventory [0]
    armor = inventory [1]
    caterpillar = inventory [2]
    navSys = inventory [3]
    context = {'money' : UserProfile.objects.get(user=request.user).money,
               'username' : request.user,
               'pageIn': 'inventory',
               'weaponInv': weapon,
               'armorInv': armor,
               'caterInv': caterpillar,
               'navInv': navSys,
               'tank': Tank.objects.get(owner=UserProfile.objects.get(user=request.user))
               }
    return render(request, 'backend/inventaire.html',context)

@login_required
def parameter(request):

    form = ChangeDataForm()
    form.fields['email'].initial = request.user.email
    form.fields['username'].initial= request.user.username
    context = {'money' : UserProfile.objects.get(user=request.user).money,
               'username' : request.user,
               'form': form}
    return render(request, 'backend/parameter.html',context)

@login_required
def help(request):
    context = {'money' : UserProfile.objects.get(user=request.user).money,
               'username' : request.user,
               'pageIn': 'help'}
    return render(request, 'backend/aide.html',context)

@login_required
def agression(request):
    userProfile = UserProfile.objects.get(user=request.user)
    agressionValue = userProfile.agression
    userProfile.agression = not agressionValue
    userProfile.save()
    return redirect(reverse('backend:index'))

@login_required
def changeStuff(request):
    userProfile = UserProfile.objects.get(user=request.user)
    tank = Tank.objects.get(owner=userProfile)
    itemIn = request.POST.get("item")
    typeIn = request.POST.get("typeItem")
    if int(typeIn) == 1:
        w = getItemByType(itemIn, TypeItem(pk=1))
        tank.weapon = w
        tank.save()
    elif int(typeIn) == 2:
        a = getItemByType(itemIn, TypeItem(pk=2))
        tank.armor = a
        tank.save()
    elif int(typeIn) == 3:
        c = getItemByType(itemIn, TypeItem(pk=3))
        tank.caterpillar = c
        tank.save()
    elif int(typeIn) == 4:
        n = getItemByType(itemIn, TypeItem(pk=4))
        tank.navSystem = n
        tank.save()
    return redirect(reverse('backend:inventory'))

@login_required
def buyStuff (request):

WebPyRobot/backend/templates/backend/editeur.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>WebPyRobot - Editeur</title>

    {% include 'backend/head.html' %}

    <!-- Editeur Python CSS -->
    <link rel="stylesheet" href="{% static 'codemirror/lib/codemirror.css' %}"/>
    <link rel="stylesheet" href="{% static 'codemirror/theme/elegant.css' %}"/>
    <script src="{% static 'codemirror/lib/codemirror.js' %}"></script>
    <script src="{% static 'codemirror/mode/python/python.js' %}"></script>
    <script src="{% static 'codemirror/addon/edit/closebrackets.js' %}"></script>
    <script src="{% static 'codemirror/addon/edit/matchbrackets.js' %}"></script>
  </head>
  <body>
    {% include 'backend/header.html' with moneyIn=money user=username%}
    <main class="container">
      <div class="section">
        <div class="row">

            {% include 'backend/sideNav.html' with page=pageIn %}

          <div class="col s12 m9 l10 pad">
            <div class="row z-depth-1 section padding-section">
              <div class="pad row col s12 m12 l12 ">
                <div class="pad col s12 m12 l12 ">
                  <nav>
                    <div class="nav-wrapper">
                      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
                      <ul class="left hide-on-med-and-down">
                        <li class="save"><a href="#">Sauvgarder</a></li>
                        <li><a href="{% url 'backend:fight' %}">Tester</a></li>
                      </ul>
                      <ul class="side-nav" id="mobile-demo">
                        <li class="save"><a class="waves-effect" href="#"><i class="material-icons left">save</i>Sauvgarder</a></li>
                        <li><a class="waves-effect" href="#"><i class="material-icons left">cached</i>Tester</a></li>
                      </ul>
                    </div>
                  </nav>
                </div>
                <div class="pad col s12 m12 l12">
                    <form id="code" action="{% url 'backend:editor' %}" method="post">
                        {% csrf_token %}
                        <textarea name="ia" id="ia" cols="40" rows="10">{{ code }}</textarea>
                    </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    {% include 'backend/footer.html' %}
    <script src="{% static 'js/editor.js' %}"></script>
    </body>
</html>

WebPyRobot/backend/templates/backend/head.html
    {% load static %}

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>

WebPyRobot/backend/templates/backend/index.html
{% load static %}
<!DOCTYPE html>
<html lang="fr" xmlns="http://www.w3.org/1999/html">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Bienvenue sue WebPyRobot</title>

  {% include 'backend/head.html' %}

</head>
<body>
  <header>
    <nav class="light-blue lighten-1" role="navigation">
      <div class="nav-wrapper container"><a id="logo-container" href="index" class="brand-logo"><img class="img-logo" src="{% static "img/svg_tank/tank.svg" %}">  WebPyRobot</a>
        <ul class="right hide-on-med-and-down">
          <li><a class="modal-trigger" href="#modalConnexion">Connexion</a></li>
          <li><a class="modal-trigger" href="#modalInscription">Inscription</a></li>
        </ul>

        <ul id="nav-mobile" class="side-nav">
          <li><a class="modal-trigger" href="#modalConnexion">Connexion</a></li>
          <li><a class="modal-trigger" href="#modalInscription">Inscription</a></li>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      </div>
    </nav>
  </header>
  {% if error %}
  <p>{{ error }}</p>
  {% endif %}

  <!-- MODAL  -->
  <div id="modalConnexion" class="modal">
    <div class="modal-content">
      <h4>Connexion</h4>
      <form method="post" action="{% url 'backend:login' %}">
        <div class="row">
          {% csrf_token %}
          <div class="input-field col s12">
            <input placeholder="Placeholder" id="username" name="username" type="text" class="validate">
            <label for="first_name">Pseudo</label>
          </div>
          <div class="input-field col s12">
            <input id="password" name="password" type="password" class="validate">
            <label for="password">Password</label>
          </div>
          <div class="modal-footer">
           <input type="submit" value="Se Connecter" class=" modal-action waves-effect waves-green btn">
         </div>
       </div>
     </form>

   </div>
 </div>
 <div id="modalInscription" class="modal">
  <div class="modal-content">
    <form action="{% url 'backend:signUp' %}" method="post">
      {% csrf_token %}
      <h4>Inscription</h4>
      <div class="row">

        <div class="input-field col s12">
          {{ form.username }}
          <label for="{{ form.username.label }}">{{ form.username.label }}</label>
        </div>
        <div class="input-field col s12">
          {{ form.email }}
          <label for="{{ form.email.label }}">{{ form.email.label }}</label>
        </div>
        <div class="input-field col s12">
          {{ form.password }}
          <label for="{{ form.password.label }}">{{ form.password.label }}</label>
        </div>
      </div>

      <div class="modal-footer">
        <input type="submit" value="S'inscrire" class=" modal-action waves-effect waves-green btn">
      </div>
    </form>
  </div>
</div>

<main class="container">
  <div class="section">

    <!--   Icon Section   -->
    <div class="row">
      <div class="col s12">
        <div class="icon-block">
          <h2 class="center light-blue-text"><i class="material-icons">flash_on</i></h2>
          <h5 class="center">WebPyRobot</h5>

          <div class="flow-text justify"><p>WebPyrobot est un projet réalisé par des étudiants.<br>
            Notre site à pour but d'apprendre à coder en un langage très répandu et pratique pour débuter.<br/>
            Sur WebPyRobot créez la plus puissante intelligence artificielle qui contrôlera votre tank et détruisez vos ennemies.
              Simple et gratuit notre site vous permettra de montrer vos talents de développeur. <br/>
              Rejoignez vite notre communauté.
            </p>
          </div>
        </div>
      </div>
    </div>

  </div>
  <!-- Gallery Section -->
  <div class="section">
    <div class="carousel">
      <a class="carousel-item" href="#two!"><img src="{% static 'img/python_logo.png' %}"></a>
      <a class="carousel-item" href="#three!"><img src="{% static 'img/tank.png' %}"></a>
      <a class="carousel-item" href="#four!"><img src="{% static 'img/équipement.png' %}"></a>
       <a class="carousel-item" href="#five!"><img src="{% static 'img/intelligence-artificielle.jpg' %}"></a>
      <a class="carousel-item" href="#one!"><img src="{% static 'img/game.png' %}"></a>
    </div>
  </div>
</main>
{% include 'backend/footer.html' %}

</body>
</html>

WebPyRobot/backend/templates/backend/login.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    {% if error %}
    <p>{{ error }}</p>
    {% endif %}

    {% if next %}
        <p>Please login to see the {{ next }}.</p>
    {% endif %}

    <form method="post" action="{% url 'backend:login' %}">
        {% csrf_token %}
        <input type="text" name="username" value="test"/>
        <input type="text" name="password" value="testtest1"/>
        {% if next %}
        <input type="hidden" name="next" value="{{ next }}" />
        {% endif %}
        <input type="submit" value="login" />
    </form>
    <a href="{% url 'backend:signUp' %}">Or sign up</a>
</body>
</html>

WebPyRobot/backend/templates/backend/thanks.html
{% load static %}
<!DOCTYPE html>
<html lang="fr" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>Bienvenue sue WebPyRobot</title>

    {% include 'backend/head.html' %}

  </head>
  <body>
    <header>
        <nav class="light-blue lighten-1" role="navigation">
          <div class="nav-wrapper container"><a id="logo-container" href="index" class="brand-logo"><img class="img-logo" src="{% static "img/svg_tank/tank.svg" %}">  WebPyRobot</a>
            <ul class="right hide-on-med-and-down">
              <li><a class="modal-trigger" href="#modalConnexion">Connexion</a></li>
              <li><a class="modal-trigger" href="#modalInscription">Inscription</a></li>
            </ul>

            <ul id="nav-mobile" class="side-nav">
              <li><a class="modal-trigger" href="#modalConnexion">Connexion</a></li>
              <li><a class="modal-trigger" href="#modalInscription">Inscription</a></li>
            </ul>
            <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
          </div>
        </nav>
    </header>
    {% if error %}
        <p>{{ error }}</p>
    {% endif %}

      <!-- MODAL  -->
    <div id="modalConnexion" class="modal">
        <div class="modal-content">
          <h4>Connexion</h4>
            <form method="post" action="{% url 'backend:login' %}">
              <div class="row">
              {% csrf_token %}
                  <div class="input-field col s12">
                    <input placeholder="Placeholder" id="username" name="username" type="text" class="validate">
                    <label for="first_name">Pseudo</label>
                  </div>
                  <div class="input-field col s12">
                    <input id="password" name="password" type="password" class="validate">
                    <label for="password">Password</label>
                  </div>
                 <div class="modal-footer">
                   <input type="submit" value="Se Connecter" class=" modal-action waves-effect waves-green btn">
                 </div>
               </div>
            </form>

        </div>
      </div>
    <div id="modalInscription" class="modal">
        <div class="modal-content">
            <form action="{% url 'backend:signUp' %}" method="post">
            {% csrf_token %}
                <h4>Inscription</h4>
                <div class="row">

                    <div class="input-field col s12">
                        {{ form.username }}
                        <label for="{{ form.username.label }}">{{ form.username.label }}</label>
                    </div>
                    <div class="input-field col s12">
                        {{ form.email }}
                        <label for="{{ form.email.label }}">{{ form.email.label }}</label>
                    </div>
                    <div class="input-field col s12">
                        {{ form.password }}
                        <label for="{{ form.password.label }}">{{ form.password.label }}</label>
                    </div>
                </div>
                    
                <div class="modal-footer">
                    <input type="submit" value="S'inscrire" class=" modal-action waves-effect waves-green btn">
                </div>
            </form>
        </div>
    </div>

    <main class="container">
      <div class="section">

        <!--   Icon Section   -->
        <div class="row">
            <p>Thanks to register</p>
        </div>

      </div>
      <!-- Gallery Section -->
      <div class="section">
        <div class="carousel">
          <a class="carousel-item" href="#one!"><img src="{% static 'img/galaxy.jpg' %}"></a>
          <a class="carousel-item" href="#two!"><img src="{% static 'img/galaxy.jpg' %}"></a>
          <a class="carousel-item" href="#three!"><img src="{% static 'img/galaxy.jpg' %}"></a>
          <a class="carousel-item" href="#four!"><img src="{% static 'img/galaxy.jpg' %}"></a>
          <a class="carousel-item" href="#five!"><img src="{% static 'img/galaxy.jpg' %}"></a>
        </div>
      </div>
    </main>
    {% include 'backend/footer.html' %}

    </body>
</html>